version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-rocks
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
  app:
    build: 
      context: node
    container_name: app-rocks-api
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["npm", "run", "start"]
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app-rocks
      - /usr/src/app-rocks/node_modules
    tty: true
    ports:
      - 4200:4200
    depends_on: 
      - db
  nginx:
    build: 
      context: ./nginx
    container_name: nginx-rocks
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

networks: 
  node-network:
    driver: bridge 